### ISSUE TITLE
Raspberry Pi Crashing on Request to query Simbad data base

### ISSUE THREAD

**Issue by steelewool** [steelewool/cgem-controller#36]
Here is the result running on pi:

python messierObjectList.py 
main program entered
meanLST                      :  10h12m54.0092s
10 12 54
Traceback (most recent call last):
  File "messierObjectList.py", line 72, in <module>
    messierObjects = MessierObjectList()
  File "messierObjectList.py", line 44, in __init__
    table = Simbad.query_object ('M *', wildcard=True, verbose=False, get_query_payload=False)
TypeError: query_object() got an unexpected keyword argument 'get_query_payload'
p

**Comment by steelewool** [comment]
The following line is causing me problems on my Raspberry Pi. The version of Simbad.query_object use on the pi doesn't understand the get_query_payload argument.  Here is the line that worked on the pi:
  
     table = Simbad.query_object ('M *', wildcard=True, verbose=False)
        # errors on Pi: , get_query_payload=False)

I'm wondering
a) is there a way to know which version of the Simbad.query_object I'm using at runtime? If there is maybe I can branch to the different options of the call.
b) Is there a way to know at run time which machine I'm on (pi vs. linux) and then branch to the different options.

Any thoughts on this @zcsteele

**Comment by steelewool** [comment]
With updates problem has gone away.
