### ISSUE TITLE
Bug in testSerial.py current being worked.

### ISSUE THREAD

**Issue by steelewool** [steelewool/cgem-controller#87]
In requestHighPrecisionRaDec
requestHighPrecisionRaDec, bytes 1-17:  57   56   53   70   54   51   48   48   44   48   69   49   49   49   53   48   48
telescopeRaDecCgem:  b'985F6300,0E111500#'
Traceback (most recent call last):
  File "testSerial.py", line 43, in <module>
    args = telescopeRaDecCgemI.split(',',2)
TypeError: a bytes-like object is required, not 'str'

**Comment by steelewool** [comment]
telescopeRaDecCgem:  [b'C7F4C100', b'1E71E900']
RA  :  [18, 44, 45]
Dec :  [42, 48, 47]
In gotoCommandWithHP
Traceback (most recent call last):
  File "testSerial.py", line 49, in <module>
    cgemI.gotoCommandWithHP (raFromCgem, decFromCgem)
  File "/home/pi/git/cgem-controller/cgemInterface.py", line 199, in gotoCommandWithHP
    raToCgem  = ra.toCgem()
AttributeError: 'list' object has no attribute 'toCgem'
